file:
  upload-dir: /path/to/upload/directory
logging:
  file:
    name: /logs/farmstory.log
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
        sql: debug
      mybatis: error
      springframework:
        web: error
    root: info

server:
  port: 8080
  servlet:
    context-path: /

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
spring:
  application:
    name: farmstory
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1234
    url: jdbc:mysql://localhost:3306/springfarmstory?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    jpa:
      database: mysql
      hibernate:
        ddl-auto: update
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true
          use_sql_comments: true
      show-sql: true
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
    thymeleaf:
      cache: false
      check-template-location: true
      dialect:
        springsecurity:
          enabled: true
      enabled: true
      mode: HTML
      prefix: classpath:/templates/
      suffix: .html
    # Email
    mail:
      host: smtp.gmail.com
      port: 587
      username: {woo24465@gmail.com}
      password: {mawj nxfq tiwx regc}
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
              required: true
            connectiontimeout: 5000
            timeout: 5000
            writetimeout: 5000
      auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30?